services:
  next_web:
    container_name: next_web
    image: youtube-summarize-nextjs
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
        AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
        AUTH_SECRET: ${AUTH_SECRET}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
    ports:
      - 5566:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_URL=http://localhost:3000/api/auth
    depends_on:
      next_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully # Waits for exit code 0

  migrations:
    container_name: next_migrations
    image: youtube-summarize-migrations
    build:
      context: .
      dockerfile: ./packages/database/Dockerfile
    restart: "no"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      next_db:
        condition: service_healthy

  next_db:
    container_name: next_db
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=youtube_summarize
    ports:
      - 5433:5432
    volumes:
      - youtube_summarize_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-d",
          "youtube_summarize",
          "-h",
          "localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: next_summarize_pgadmin4_container
    restart: always
    ports:
      - "8899:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      next_db:
        condition: service_healthy

volumes:
  youtube_summarize_postgres_data:
  pgadmin-data:
