import type { Metadata } from "next";
import "@/app/styles/globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { QueryProviders } from "@/components/query-provider";
import { Sidebar } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "vercel ai video summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProviders>
            <main className="relative flex min-h-dvh w-full">
              <Sidebar />
              {children}
              <Toaster richColors={true} />
            </main>

            <Toaster richColors={true} />
            <TailwindIndicator />
          </QueryProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
